### ISSUE TITLE
[TypeError: Cannot read property 'split' of undefined]

### ISSUE THREAD

**Issue by plauge** [peterramsing/lost#268]
HI,
I've just started using PostCSS - so maybe Im the bug :-)

I'm getting this error in my terminal. If I remove lost() from the pipe(), I do not get any errors.
Only thing I found that looks as the same "bug" is this https://github.com/peterramsing/lost/issues/160 - but it did not help me.

Anybody knwo how to fix this?

Thanks!!

```
[11:55:40] { [TypeError: Cannot read property 'split' of undefined]
  name: 'TypeError',
  message: 'Cannot read property \'split\' of undefined',
  stack: 'TypeError: Cannot read property \'split\' of undefined\n    
at appendToSelectors (/Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/lost/lib/new-block.js:7:13)\n    
at newBlock (/Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/lost/lib/new-block.js:14:22)\n    
at /Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/lost/lib/lost-column.js:137:11\n    
at /Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:98:28\n    
at /Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:73:26\n    
at AtRule.each (/Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:60:22)\n    
at AtRule.walk (/Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:72:21)\n    
at /Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:75:32\n    
at Rule.each (/Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:60:22)\n    
at Rule.walk (/Applications/MAMP/htdocs/wwwroot/myWebsite/wp-content/themes/pixelhuset16/node_modules/postcss/lib/container.js:72:21)',
```

Here is how my dependencies looks in my package.json fil:

```
  "devDependencies": {
    "autoprefixer": "^6.3.3",
    "cssnano": "^3.5.2",
    "cssnext": "^1.8.4",
    "gulp": "^3.9.1",
    "gulp-cssnano": "^2.1.1",
    "gulp-postcss": "^6.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-util": "^3.0.7",
    "gulp-webserver": "^0.9.1",
    "lost": "^6.7.2",
    "postcss-color-function": "^2.0.0",
    "postcss-inline-comment": "^2.0.0",
    "precss": "^1.3.0"
  },
```

And here is my gulp file:

```
var gulp = require('gulp'),
gutil = require('gulp-util'),
webserver = require('gulp-webserver'),
postcss = require('gulp-postcss'),
sourcemaps = require('gulp-sourcemaps'),
postCSS_InlineComment = require('postcss-inline-comment');
autoprefixer = require('autoprefixer'),
precss = require('precss'),
cssnano = require('cssnano'),
cssnext = require('cssnext'),
lost = require('lost'),
colorfunctions = require('postcss-color-function'),    

source = 'dev/css/',
dest = 'front/';



gulp.task('css', function() {
  gulp.src(source + 'style.css')
  .pipe(sourcemaps.init())
  .pipe(postcss([
    autoprefixer(),
    colorfunctions(),
    precss(),
    lost(),    
    postCSS_InlineComment(),
    cssnano(),
    cssnext()
    ]))
  .on('error', gutil.log)
  .pipe(sourcemaps.write('./'))
  .pipe(gulp.dest(dest + 'css'));
});

gulp.task('watch', function() {
  gulp.watch(source + '**/*.css', ['css']);
});

gulp.task('webserver', function() {
  gulp.src(dest)
  .pipe(webserver({
    livereload: true,
    open: true
  }));
});

gulp.task('default', ['css','watch']); 
```

**Comment by plauge** [comment]
I've tried to put lost() in the beginning and in the end of the pipe(). Same result.

**Comment by peterramsing** [comment]
Just out of curiosity, what if you put `autoprefixer()` after `lost()`?

**Comment by plauge** [comment]
Sorry - Im new to PostCSS.
After some more test, I can see that some of my SASS code not was converted correct.

BTW - very nice library! Im coming from the Susy grid.

**Comment by peterramsing** [comment]
@plauge Super. Glad you got it sorted and thanks!
