### ISSUE TITLE
webpack lost complie fails

### ISSUE THREAD

**Issue by terion-name** [peterramsing/lost#366]
Can't figure out why this happens:

```
$ npm ls postcss
└── postcss@5.2.17 

$ npm ls lost
└── lost@6.8.1 
```
```
 ERROR  Failed to compile with 3 errors                                                                                                                                                                                  6:12:42 PM

 error  in ./resources/assets/stylus/app.styl

Module build failed: TypeError: css.walkAtRules is not a function
    at lostAtRule (.../node_modules/lost/lib/lost-at-rule.js:12:7)
    at .../node_modules/lost/lost.js:32:7
    at Array.forEach (native)
    at Renderer.<anonymous> (.../node_modules/lost/lost.js:31:10)
    at Renderer.use (.../node_modules/stylus/lib/renderer.js:204:6)
    at .../node_modules/stylus-loader/index.js:66:16
    at Array.forEach (native)
    at .../node_modules/stylus-loader/index.js:64:25
    at Array.forEach (native)
    at Object.module.exports (.../node_modules/stylus-loader/index.js:61:24)

```

**Comment by peterramsing** [comment]
@terion-name What order do you have the transpilation happening in? ...is LostGrid after the Stylus is transpiled into CSS? (LostGrid should be **after** your Stylus turns into CSS)

**Comment by terion-name** [comment]
@peterramsing sorry, error is not related to lost, already figured out
